name: Scrape Reddit to Artifact

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'URL to scrape'
        required: true
        default: 'https://old.reddit.com/r/webdev/'

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  scrape-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Scrape the website
        run: |
          mkdir -p scraped_page
          cd scraped_page
          
          wget -p -k -E \
            --header="Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8" \
            --header="Accept-Language: en-US,en;q=0.5" \
            --header="Accept-Encoding: gzip, deflate, br" \
            --header="Connection: keep-alive" \
            --header="Upgrade-Insecure-Requests: 1" \
            --header="Sec-Fetch-Dest: document" \
            --header="Sec-Fetch-Mode: navigate" \
            --header="Sec-Fetch-Site: none" \
            --header="Sec-Fetch-User: ?1" \
            -U "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:125.0) Gecko/20100101 Firefox/125.0" \
            "${{ github.event.inputs.url }}" || true

      - name: Zip the scraped files
        run: |
          # Go back to root workspace to zip the folder
          cd ${{ github.workspace }}
          zip -r scraped_data.zip scraped_page/

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: scraped-website-files
          path: scraped_data.zip
          retention-days: 7
